nelmio_cors:
  defaults:
    allow_credentials: true
    allow_origin: ["http://localhost:4200", "http://localhost:8000"] # Add all the domains you need
    allow_headers: ["*"]
    expose_headers: ["Authorization"]
    allow_methods: ["POST", "GET", "OPTIONS", "PUT", "DELETE"]
    max_age: 3600

  paths:
    ^/.*:
      allow_origin: ["http://localhost:4200", "http://localhost:8000"] # Adjust this path as per your API endpoint
